"use client";

import { useEffect, useRef } from "react";
import { useStudio } from "@/contexts/StudioContext";
import { useGeneration } from "@/hooks/useGeneration";
import { DataGrid } from "@/components/grid/DataGrid";
import { GenerateButton } from "../GenerateButton";
import { getTemplateFields } from "@/lib/engine";
import { Sparkles, ArrowRight } from "lucide-react";

export function Step4Preview() {
  const { state, dispatch } = useStudio();
  const { generate, isGenerating, progress, error } = useGeneration();
  const fields = getTemplateFields(state.config.template ?? "crm");
  const hasAutoGenerated = useRef(false);

  // Auto-generate on first visit to this step
  useEffect(() => {
    if (!hasAutoGenerated.current && !state.dataset && !isGenerating) {
      hasAutoGenerated.current = true;
      generate();
    }
  }, [generate, state.dataset, isGenerating]);

  const handleGenerate = () => {
    generate();
  };

  const handleCellEdit = (rowId: string, field: string, value: unknown) => {
    dispatch({ type: "EDIT_CELL", rowId, field, value });
  };

  const goNext = () => {
    dispatch({ type: "SET_STEP", step: 5 });
  };

  return (
    <div className="flex flex-col h-full">
      {/* Top bar */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-ds-border glass-panel-strong shrink-0">
        <div>
          <h2 className="text-sm font-semibold text-ds-text-primary font-display">
            Data Preview
          </h2>
          {state.dataset && (
            <p className="text-[11px] text-ds-text-tertiary mt-0.5 font-data">
              {state.dataset.rows.length.toLocaleString()} rows &middot;
              generated in {state.dataset.durationMs}ms
            </p>
          )}
        </div>
        <div className="flex items-center gap-2">
          <GenerateButton
            onClick={handleGenerate}
            isLoading={isGenerating}
            progress={progress}
            hasData={!!state.dataset}
          />
          {state.dataset && (
            <button
              type="button"
              onClick={goNext}
              className="group h-10 px-5 rounded-xl glass-panel text-ds-text-primary text-sm font-medium transition-all hover:bg-ds-bg-elevated/60 inline-flex items-center gap-2"
            >
              Export
              <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
            </button>
          )}
        </div>
      </div>

      {/* Grid fills remaining height */}
      <div className="flex-1 overflow-hidden p-4">
        {state.dataset ? (
          <DataGrid
            rows={state.dataset.rows}
            fields={fields}
            isAnimating={isGenerating}
            onCellEdit={handleCellEdit}
          />
        ) : (
          <div className="flex flex-col items-center justify-center h-full">
            <div className="w-14 h-14 rounded-2xl bg-ds-accent-muted flex items-center justify-center mb-5">
              <Sparkles className="w-7 h-7 text-ds-accent" />
            </div>
            <h3 className="text-base font-medium text-ds-text-primary mb-1 font-display">
              {isGenerating ? "Generating your data..." : "Ready to generate"}
            </h3>
            <p className="text-sm text-ds-text-secondary mb-5">
              {isGenerating
                ? "This should only take a moment"
                : "Click generate to create your dataset"}
            </p>
            {isGenerating && (
              <div className="w-56 h-2 bg-ds-bg-tertiary rounded-full overflow-hidden">
                <div
                  className="h-full bg-ds-accent rounded-full transition-all duration-200"
                  style={{ width: `${progress}%` }}
                />
              </div>
            )}
          </div>
        )}
      </div>

      {error && (
        <div className="px-6 py-3 bg-ds-destructive/10 border-t border-ds-destructive/30 text-sm text-ds-destructive">
          {error}
        </div>
      )}
    </div>
  );
}
