"use client";

import { useEffect, useRef } from "react";
import { useStudio } from "@/contexts/StudioContext";
import { useGeneration } from "@/hooks/useGeneration";
import { DataGrid } from "@/components/grid/DataGrid";
import { GenerateButton } from "../GenerateButton";
import { getTemplateFields } from "@/lib/engine";
import { Sparkles } from "lucide-react";

export function Step4Preview() {
  const { state, dispatch } = useStudio();
  const { generate, isGenerating, progress, error } = useGeneration();
  const fields = getTemplateFields(state.config.template ?? "crm");
  const hasAutoGenerated = useRef(false);

  // Auto-generate on first visit to this step
  useEffect(() => {
    if (!hasAutoGenerated.current && !state.dataset && !isGenerating) {
      hasAutoGenerated.current = true;
      generate();
    }
  }, [generate, state.dataset, isGenerating]);

  const handleGenerate = () => {
    generate();
  };

  const handleCellEdit = (rowId: string, field: string, value: unknown) => {
    dispatch({ type: "EDIT_CELL", rowId, field, value });
  };

  const goNext = () => {
    dispatch({ type: "SET_STEP", step: 5 });
  };

  return (
    <div className="flex flex-col h-full">
      {/* Top bar */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-ds-border shrink-0">
        <div>
          <h2 className="text-sm font-semibold text-ds-text-primary">
            Data Preview
          </h2>
          {state.dataset && (
            <p className="text-[11px] text-ds-text-secondary mt-0.5 font-data">
              {state.dataset.rows.length.toLocaleString()} rows &middot;
              generated in {state.dataset.durationMs}ms
            </p>
          )}
        </div>
        <div className="flex items-center gap-2">
          <GenerateButton
            onClick={handleGenerate}
            isLoading={isGenerating}
            progress={progress}
            hasData={!!state.dataset}
          />
          {state.dataset && (
            <button
              onClick={goNext}
              className="h-9 px-4 rounded-md bg-ds-bg-secondary border border-ds-border hover:bg-ds-bg-tertiary text-ds-text-primary text-sm font-medium transition-colors"
            >
              Export
            </button>
          )}
        </div>
      </div>

      {/* Grid fills remaining height */}
      <div className="flex-1 overflow-hidden p-4">
        {state.dataset ? (
          <DataGrid
            rows={state.dataset.rows}
            fields={fields}
            isAnimating={isGenerating}
            onCellEdit={handleCellEdit}
          />
        ) : (
          <div className="flex flex-col items-center justify-center h-full">
            <div className="w-12 h-12 rounded-full bg-ds-accent/10 flex items-center justify-center mb-4">
              <Sparkles className="w-6 h-6 text-ds-accent" />
            </div>
            <h3 className="text-sm font-medium text-ds-text-primary mb-1">
              {isGenerating ? "Generating your data..." : "Ready to generate"}
            </h3>
            <p className="text-xs text-ds-text-secondary mb-4">
              {isGenerating
                ? "This should only take a moment"
                : "Click generate to create your dataset"}
            </p>
            {isGenerating && (
              <div className="w-48 h-1.5 bg-ds-bg-tertiary rounded-full overflow-hidden">
                <div
                  className="h-full bg-ds-accent rounded-full transition-all duration-200"
                  style={{ width: `${progress}%` }}
                />
              </div>
            )}
          </div>
        )}
      </div>

      {error && (
        <div className="px-6 py-3 bg-red-500/10 border-t border-red-500/30 text-sm text-red-400">
          {error}
        </div>
      )}
    </div>
  );
}
